#!/bin/bash

if [ -z "$CFILE" ]; then
   echo "ERROR: Please give a c file name as an arg"
   exit 1
fi

if [ ! -f "CFILE" ]; then
   echo "ERROR: File '$CFILE' does not exist."
   exit 1
fi

gcc -S -o "$file_base.s" "$CFILE"

echo "Created assembly code for '$CFILE' in '$file_base.s."