#!/bin/bash

if [ -z "$CFILE" ]; then
   echo "ERROR: Provide  c file name as an arg."
   exit 1
fi

if [ ! -f "$CFILE" ]; then
   echo "ERROR: file '$CFILE' cant be found."
   exit 1
fi

gcc "$CFILE" -o cisfun

echo "Compiled '$CFILE' and creared 'cisfun' as executable."